name: Continuous Integration

on:
  push:
    branches: [dev]
  pull_request:
    branches: [main, dev]

jobs:
  test:
    name: Run Tests and Quality Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js with Cache
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint check
        run: npm run lint

      - name: Build check
        run: npm run build

      - name: Run unit tests
        run: npm test -- --passWithNoTests
