name: Production Deployment

on:
  workflow_dispatch:

jobs:
  call-deploy:
    name: Trigger Prod Deploy
    uses: ./.github/workflows/deploy-shared.yml
    with:
      environment_name: prod
      runner_tag: prod
      include_local_db: false
    secrets: inherit
